### ISSUE TITLE
Error in running the dropui igcn.dropui baseline. 

### ISSUE THREAD

**Issue by Prishruit** [WuYunfan/Inductive-Graph-Convolution-Network-for-Recommendation#7]
I was able to run the baseline successfully - 1. python -u -m run.run and 2. python -u -m run.dropit.igcn_dropit , but in the case where both user and items are new that is igcn_dropui, the code gives an error, so when I run this command  - python -u -m run.dropui.igcn_dropui : I get `FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/...' ` at File 

`run/dropui/igcn_dropui.py", line 38, in main
    model.load('checkpoints/...')`

the checkpoint directory does exist and the model is also getting saved there, if I make some changes and then use the saved model in that directory I get this error `size mismatch for embedding.weight: copying a param with shape torch.Size([56678, 64]) from checkpoint, the shape in current model is torch.Size([70848, 64]).` .

**Comment by WuYunfan** [comment]
This part of code is to show the inductive evaluation results of the retrained model. In the original paper, it corresponds to "INMO-LGCN-retrain". So if you need to run this code, you can train a model on the full dataset (e.g., "0,1,2,3,4") and rename the saved checkpoint file to "...". Otherwise, you can delete this codes.
